name: WordPress CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate-k8s-manifests:
    name: Validate Kubernetes Manifests (CI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install kubeval
        run: |
          curl -sSL https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz | tar -xz -C /usr/local/bin

      - name: Validate Kubernetes Manifests
        run: |
          kubeval --strict *.yml

  deploy-to-kubernetes:
    name: Deploy to Kubernetes (CD)
    needs: validate-k8s-manifests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      # Configure kubeconfig file
      - name: Configure kubeconfig
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}  # Assuming the kubeconfig is stored in GitHub Secrets
        run: |
          # Write the KUBECONFIG content into the default .kube/config file
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_FILE}" > $HOME/.kube/config

          # Verify the content
          echo "Kubeconfig content:"
          cat $HOME/.kube/config

      # Apply Kubernetes manifests
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f . -v=8

      # Verify deployment
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/wordpress
          kubectl get svc wordpress -o wide

